### ISSUE TITLE
yaml file color definitions not applying

### ISSUE THREAD

**Issue by vegerot** [athityakumar/colorls#246]
### Description
`colorls` does not use the custom color configuration as specified in `lib/yaml`.  The only colors that are given are "Main Colors" for recognized/unrecognized files, and directories.  No other colors are shown. For example, executables are not red, no age colors, no file size colors, no git colors, etc.

Speculation: This may have something to do with the priority of the yaml.  It should first look at categories such as access, and if nothing applies, then apply the "Main Color".  But instead it will only apply the "Main Color".

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by mstill3** [comment]
I also have this issue.  All my recognized files are lime

**Comment by avdv** [comment]
That is not a bug, it is how the colorization works currently.

The file *name* is _always_ colored according to whether it is a recognized file or not (colorization for special files like sockets and devices is yet to be released).

Only in the long listing format (`--long`) are parts of the information colored differently and this the only place where the other colors are used.

The modification time column is colored in a different color when it changed in the last hour, or the last 24 hours.

In the same way, a file's mode characters are colored according to the the colors given for the executable, readable, writable and no-access colors.

And a file's *size* is colored according to whether it is a large, medium or small file.

Look at this screenshot:
![](https://user-images.githubusercontent.com/17109060/32149049-2a63ae48-bd25-11e7-943c-5ceed25bd693.png)

The `x` of the mode column is red. This is where the `exec` color gets used.

The modification time of has a lighter green than most other files, since it was apparently modified in the last 24 hours, the LICENSE file was changed even more recently.

**Comment by vegerot** [comment]
So is there no way to have certain filetypes colored differently?  In Bash, I have executables and different types of files colored differently depending on their extension.  How do I color the file names by either/or extension or access permissions?

**Comment by avdv** [comment]
> So is there no way to have certain filetypes colored differently?

No, currently not.

> In Bash, I have executables and different types of files colored differently depending on their extension.

That is actually done by GNU ls according to your LS_COLORS env variable. We might add support for this some time later.

**Comment by vegerot** [comment]
Unfortunately there's no way to even color symlinks differently :(

/close
