### ISSUE TITLE
Alias not working

### ISSUE THREAD

**Issue by ueberBrot** [athityakumar/colorls#294]
### Description

I'm trying to set aliases in my `.zshrc` file for certain `colorls` commands.
That das not work for me.

The specified aliases:
```zsh
alias ll="colorls -lA --sd"
alias ls="colorls --gs --sd" 
```
Now when i use the specified alias what happens is the normal `ls` or `ll` command will be executed.

`colorls` with the above flags functions fine.

My setup:
OS: Manjaro Linux 18.0.4 Illyria Gnome Desktop
Terminal emulator: [Tilix](https://gnunn1.github.io/tilix-web/)
zsh: zsh 5.7.1 (x86_64-pc-linux-gnu) + [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) + [powerlevel10k theme](https://github.com/romkatv/powerlevel10k)
Fonts: [Hack Fonts Mono Regular](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack/Regular/complete)

Not sure what box to tick. Because it has to do with initial setup maybe its **Installation**?

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by ueberBrot** [comment]
I switched to [lsd](https://github.com/Peltoche/lsd).

And as stated [here](https://github.com/romkatv/powerlevel10k/issues/86#issuecomment-501347702) I wont be using aliases.

**Comment by avdv** [comment]
FTR, if your aliases in your Shell are not working, there is nothing colorls can do about it, there's probably some different config you sourced which overrode the aliases you created. Look at the output of `alias` the next time.

Also, I am using aliases because I do not want to train my fingers to another command which does not exist on other systems, having to keep in mind which system has colorls / lsd and which does not. That's the reason for colorls trying hard to be a drop-in replacement for GNU ls in most aspects, but admittedly it's still a long way to go.
