### ISSUE TITLE
Fonts not loading...

### ISSUE THREAD

**Issue by tr1s** [athityakumar/colorls#320]
### Description

Honestly I have no idea how to do this. I can't find clear instructions anywhere :(

I don't understand how to `./install.sh`, it just says no such directory.

Colorls fonts say to download powerline patched but it's not even in the Nerd-fond repo

I've tried installing fonts with brew cask, and I see it work, but then I add "FiraCode-Light" to my hyper terminal config for fonts, but then I start getting these weird red percentage symbols, and still no icons.

What am I missing here?

<img width="1313" alt="Hyper 2019-10-15 at 21 08 48@2x" src="https://user-images.githubusercontent.com/19172250/66880418-d8044b80-ef90-11e9-9f73-6a880b5a5ee4.png">

<img width="75" alt="CleanShot 2019-10-15 at 21 12 39@2x" src="https://user-images.githubusercontent.com/19172250/66880348-88be1b00-ef90-11e9-8de1-40f8ee59b77c.png">

<img width="184" alt="CleanShot 2019-10-15 at 21 11 12@2x" src="https://user-images.githubusercontent.com/19172250/66880334-747a1e00-ef90-11e9-90dc-a3820aad4ad8.png">

**Comment by avdv** [comment]
FiraCode-Light is wrong, as this is the original font but you need to use a patched font. The corresponding patched font from nerdfonts is called FuraCode Nerd-Light.

**Comment by tr1s** [comment]
@avdv How come there's no clear instructions to download a patched font? I clicked the download and it takes me [here](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode). I've tried downloading manually and activating the fonts, and threw brew/cask. Each just give me the regular FireCode font...

I can't be the only one incredible confused by all this :/

**Comment by avdv** [comment]
> @avdv How come there's no clear instructions to download a patched font?

I guess you need to pay more attention to the details.

> I don't understand how to `./install.sh`, it just says no such directory.

It clearly says in the nerdfonts README, that you have to clone the repo first, in order to call [`install.sh`](https://github.com/ryanoasis/nerd-fonts/blob/master/install.sh), which is part of their repo.

> I've tried downloading manually and activating the fonts, and threw brew/cask.

You installed the wrong font with that brew command. You need to install one of the fonts with *nerd* in their name, e.g. `brew cask install font-hack-nerd-font`.

> I can't be the only one incredible confused by all this :/

We don't have much questions about installing the fonts, so it seems there are no such obstacles for most other people. But in the end, installing fonts is very different for each platform and that's not  a problem colorls can solve. Better ask over at nerdfonts if you have difficulties installing the fonts.

**Comment by tr1s** [comment]
So I'm supposed to guess the cask command for the font I want lol? 

I see the problem here though, I should have went to their website. The website has all the proper nerd font downloads, the github repo just links to all the originals.

Anyway yeah, this is not a colorls issue so I'll just close and move on.
