### ISSUE TITLE
Support for clubbed flag options, like -al

### ISSUE THREAD

**Issue by elFua** [athityakumar/colorls#74]
`-a` works on its own, and `-l` works on its own, but when combined to `-al` (like in GNU ls) it does not produce the expected output. Specifying them as separate arguments (`colorls -a -l`) has the expected behaviour.

**Comment by athityakumar** [comment]
@elFua - Accepted, thanks for filing this issue. 😄 

As you've specified above, `colorls -a -l` is intended to work like that. Each flag is implemented separately and support for usage of clubbed flags like `-al` is pending.

If anyone would like to contribute for this, the `ColorLS::Flags#flag_given` method is the one that needs to be tweaked. (Check with `String#include` rather than `Array#include`, if only one flag option seems to have been given)

**Comment by adimasuhid** [comment]
hi @athityakumar, I tried to update `flag_given?` as suggested above. It works well for `-al`. However, it fails for `-alsd` since it matches for both `-sd` and `-d` (which is unintentional for `String#include?`). 

I'm thinking of two ways:
1. We add a condition for `-sd | -sf` as a special case
2. Perhaps rename `-sd | -sf` to a different single name flag (maybe `-D`, `-F` or whichever is in `man ls`?

What do you think?

For reference, code used below:
```
    def flag_given?(flags)
      flags.each { |flag| return true if @args.include?(flag) }

      # match exactly the format `-alphanumeric`
      clubbed_args = @args.select { |arg| arg.match(/^-[a-zA-Z]+$/) }.reduce(:+)
      flags.each { |flag| return true if clubbed_args.include?(flag.delete("-")) }

      false
    end
```

**Comment by GladOSkar** [comment]
To me, something like `-s=d` or `-s d` seems to be the more standard way to do it

**Comment by athityakumar** [comment]
@adimasuhid @GladOSkar - For flags with more than one character (like `sd`), I'd like to assume it would be used separately and not with clubbed flags. Something like `colorls -al -sd` seems reasonable to me. Is it good to assume that all flags in clubbed flags are each just single character?

**Comment by GladOSkar** [comment]
Yes, but multi-character short flags are pretty non-standard anyways

**Comment by athityakumar** [comment]
@GladOSkar @adimasuhid - Following from @avdv's suggestion in issue #59, would it be easier to use `optparse` to support flag inputs?
