### ISSUE TITLE
tab completion for commands

### ISSUE THREAD

**Issue by rohitner** [athityakumar/colorls#99]
`_colorls_options='-sd -sf -1 -t -r -l -a --tree --all --sort-dirs --sort-files'`
`complete -W "${_colorls_options}" 'colorls'`

adding these lines to .bashrc and doing `source ~/.bashrc` works well

**Comment by athityakumar** [comment]
@rohitner - I get your point now. Though optparse handles CLI very well, the compete isn't triggered by TAB and hence isn't intuitive. Instead of adding this in README, let's create the `sh` file from ruby script itself?

```ruby
#! tab_complete.sh.erb
_colorls_options='<%= @all_flags.join(" ") %>' complete -W "${_colorls_options}" 'colorls'
```

By parsing this template and using ERB gem to provide all the flags, we'll be able to auto-generate this `tab_complete.sh`. Only catch is that, the user would have to do something like

```console
$ gem install colorls
$ colorls tab-complete #! generates tab_complete.sh
```

and then add `source $(dirname $(gem which colorls))/tab_complete.sh` to `~/.bashrc` or `~/.zshrc`.

**Comment by rohitner** [comment]
`@all_flags` variable needs to be made. Once the flags are retrieved we can modify `.bashrc` by using `%x()` command in the ruby code itself. So step of sourcing the file will not be needed.

**Comment by athityakumar** [comment]
Yes, but directly writing to the `~/.bashrc` isn't usually a good approach. Allowing the user to source the script themselves, is more convenient.

**Comment by rohitner** [comment]
Since there is no source to retrieve all the flags, wont it be easier to maintain the shell file regularly instead of generating it?

**Comment by athityakumar** [comment]
Hmm, sounds good. Would you like to take this up, @rohitner?

**Comment by rohitner** [comment]
Sure, Working on it

**Comment by athityakumar** [comment]
Added by PR #135
